### ISSUE TITLE
Add and sync corruption repos

### ISSUE THREAD

**Issue by JoaoCarabetta** [CTS-FGV/geral#16]
- [x] corrupcao_captura
- [x] corrupcao_analise

**Comment by lucasfariaslf** [comment]
Criei os repos e inclui o notebook que comecei para exploração,

**Comment by JoaoCarabetta** [comment]
Please, put the repos in the main servers and integrate it with airflow. I can do a tutorial to help you.

**Comment by lucasfariaslf** [comment]
@JoaoCarabetta I'll need access though the analysis server jupyter notebook. I may need help with the airflow sync.  

_Sent from my Motorola XT1097 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JoaoCarabetta** [comment]
That is why I want you to work on the servers, to explore those tools. 

I will create a short tutorial for you to follow.

**Comment by lucasfariaslf** [comment]
Deal. Thanks.

**Comment by JoaoCarabetta** [comment]
Try this: https://github.com/CTS-FGV/geral/blob/master/tutoriais/Creating%20Repositories.md

**Comment by lucasfariaslf** [comment]
repos sincronizados, e airflow test retornando sem erro.
